import type { GraphData } from '../../graph'

/** 12종 kind 전부를 포함하는 샘플 SSOT 그래프 (노드 26개) — 그래프 스토리 공용 픽스처. */
export const sampleGraphData: GraphData = {
  nodes: [
    { id: 'platform-1', kind: 'Platform', label: 'Wireweave Platform' },
    { id: 'persona-1', kind: 'Persona', label: 'Solo Builder' },
    { id: 'persona-2', kind: 'Persona', label: 'Product Designer' },
    { id: 'domain-1', kind: 'Domain', label: 'Wireframe DSL' },
    { id: 'domain-2', kind: 'Domain', label: 'Design System' },
    { id: 'concept-1', kind: 'Concept', label: 'Semantic Token' },
    { id: 'concept-2', kind: 'Concept', label: 'Wireframe Spec' },
    { id: 'concept-3', kind: 'Concept', label: 'SSOT Node' },
    { id: 'capability-1', kind: 'Capability', label: 'DSL Parsing' },
    { id: 'capability-2', kind: 'Capability', label: 'Theme Switching' },
    { id: 'capability-3', kind: 'Capability', label: 'Graph Exploration' },
    { id: 'system-1', kind: 'SystemComponent', label: '@wireweave/core' },
    { id: 'system-2', kind: 'SystemComponent', label: '@wireweave/ui' },
    { id: 'system-3', kind: 'SystemComponent', label: 'api-server' },
    { id: 'integration-1', kind: 'Integration', label: 'npm Registry' },
    { id: 'integration-2', kind: 'Integration', label: 'Vercel' },
    { id: 'invariant-1', kind: 'Invariant', label: 'Semantic-only colors' },
    { id: 'invariant-2', kind: 'Invariant', label: 'WCAG 2.2 AA' },
    { id: 'decision-1', kind: 'Decision', label: 'Radix + CVA + Tailwind v4' },
    { id: 'decision-2', kind: 'Decision', label: 'react-force-graph-3d' },
    { id: 'screen-1', kind: 'Screen', label: 'Dashboard Home' },
    { id: 'screen-2', kind: 'Screen', label: 'Graph Explorer' },
    { id: 'endpoint-1', kind: 'Endpoint', label: 'GET /api/ssot/graph' },
    { id: 'endpoint-2', kind: 'Endpoint', label: 'POST /api/ssot/nodes' },
    { id: 'flow-1', kind: 'Flow', label: 'Explore SSOT Graph' },
    { id: 'flow-2', kind: 'Flow', label: 'Publish Design Token' },
  ],
  links: [
    { source: 'platform-1', target: 'domain-1', kind: 'contains' },
    { source: 'platform-1', target: 'domain-2', kind: 'contains' },
    { source: 'persona-1', target: 'flow-1', kind: 'performs' },
    { source: 'persona-2', target: 'flow-2', kind: 'performs' },
    { source: 'domain-1', target: 'concept-2', kind: 'defines' },
    { source: 'domain-2', target: 'concept-1', kind: 'defines' },
    { source: 'domain-2', target: 'concept-3', kind: 'defines' },
    { source: 'domain-1', target: 'capability-1', kind: 'provides' },
    { source: 'domain-2', target: 'capability-2', kind: 'provides' },
    { source: 'domain-2', target: 'capability-3', kind: 'provides' },
    { source: 'capability-1', target: 'system-1', kind: 'implemented-by' },
    { source: 'capability-2', target: 'system-2', kind: 'implemented-by' },
    { source: 'capability-3', target: 'system-2', kind: 'implemented-by' },
    { source: 'system-1', target: 'integration-1', kind: 'deploys-to' },
    { source: 'system-3', target: 'integration-2', kind: 'deploys-to' },
    { source: 'invariant-1', target: 'domain-2', kind: 'constrains' },
    { source: 'invariant-2', target: 'domain-2', kind: 'constrains' },
    { source: 'decision-1', target: 'system-2', kind: 'shapes' },
    { source: 'decision-2', target: 'capability-3', kind: 'shapes' },
    { source: 'screen-1', target: 'capability-2', kind: 'uses' },
    { source: 'screen-2', target: 'capability-3', kind: 'uses' },
    { source: 'screen-2', target: 'endpoint-1', kind: 'calls' },
    { source: 'system-3', target: 'endpoint-1', kind: 'serves' },
    { source: 'system-3', target: 'endpoint-2', kind: 'serves' },
    { source: 'flow-1', target: 'screen-2', kind: 'visits' },
    { source: 'flow-2', target: 'screen-1', kind: 'visits' },
    { source: 'concept-3', target: 'capability-3', kind: 'informs' },
    { source: 'concept-1', target: 'capability-2', kind: 'informs' },
  ],
}
